import Foundation

/// A minimal synchronous UCI stand-in used to drive `StockfishEngine` and
/// `PersistentStockfishEngine` without the real binary. Each call to
/// `makeLaunch` writes a fresh `/bin/sh` script to a unique temporary file;
/// parameters are baked into the script text (not passed via environment
/// variables) so parallel test classes never interfere with one another.
///
/// The script is NOT exec'd directly. The sandboxed test host may spawn
/// platform binaries such as `/bin/sh` and `/bin/cat`, but exec of a file
/// written into its own container is refused (observed 2026-09-01: `run()`
/// surfaced as `startFailed`). So the launch is `/bin/sh <script>`, via the
/// engines' `arguments:` parameter.
enum FakeUCIEngine {
    struct Script {
        var depth = 3                    // info lines emitted per `go`
        var infoDelayMs = 0              // sleep between info lines
        var extraLineAfterBestmove = false
        var exitOnGo = false             // child exits with status 3 instead of searching
        var exitOnGoOnlyOnce = false     // with exitOnGo: only the FIRST child dies; later ones search
        var exitBeforeUCI = false        // child exits immediately (launch-death route)

        init(
            depth: Int = 3,
            infoDelayMs: Int = 0,
            extraLineAfterBestmove: Bool = false,
            exitOnGo: Bool = false,
            exitOnGoOnlyOnce: Bool = false,
            exitBeforeUCI: Bool = false
        ) {
            self.depth = depth
            self.infoDelayMs = infoDelayMs
            self.extraLineAfterBestmove = extraLineAfterBestmove
            self.exitOnGo = exitOnGo
            self.exitOnGoOnlyOnce = exitOnGoOnlyOnce
            self.exitBeforeUCI = exitBeforeUCI
        }
    }

    /// What to hand an engine initialiser: `engineURL: launch.executable, arguments: launch.arguments`.
    struct Launch {
        let executable: URL
        let arguments: [String]
        let scriptURL: URL

        /// Remove the generated script and its marker file. Register with
        /// `addTeardownBlock { launch.cleanUp() }` so nothing leaks into `$TMPDIR`.
        func cleanUp() {
            try? FileManager.default.removeItem(at: scriptURL)
            try? FileManager.default.removeItem(atPath: scriptURL.path + ".died")
        }
    }

    static let shell = URL(fileURLWithPath: "/bin/sh")

    static func makeLaunch(_ script: Script = Script()) throws -> Launch {
        let delaySeconds = delayString(forMilliseconds: script.infoDelayMs)
        let scriptURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("fake-uci-engine-\(UUID().uuidString).sh")
        // Marker file for `exitOnGoOnlyOnce`: the first child creates it and exits; a later
        // child of the same script sees it and searches normally.
        let markerPath = scriptURL.path + ".died"

        let contents = """
        #!/bin/sh
        # Generated by PawnPilotTests/FakeUCIEngine.swift — do not edit by hand.
        if [ \(script.exitBeforeUCI ? 1 : 0) -eq 1 ]; then exit 2; fi
        while IFS= read -r line; do
          case "$line" in
            uci) echo "id name FakeUCI"; echo "id author PawnPilotTests"; echo "uciok" ;;
            isready) echo "readyok" ;;
            go*)
              if [ \(script.exitOnGo ? 1 : 0) -eq 1 ]; then
                if [ \(script.exitOnGoOnlyOnce ? 1 : 0) -eq 0 ] || [ ! -f "\(markerPath)" ]; then
                  touch "\(markerPath)"
                  exit 3
                fi
              fi
              d=1
              while [ $d -le \(script.depth) ]; do
                echo "info depth $d multipv 1 score cp 10 nodes 100 nps 1000 pv e2e4 e7e5"
                if [ \(script.infoDelayMs) -gt 0 ]; then sleep \(delaySeconds); fi
                d=$((d+1))
              done
              echo "bestmove e2e4 ponder e7e5"
              if [ \(script.extraLineAfterBestmove ? 1 : 0) -eq 1 ]; then echo "info string after-bestmove"; fi ;;
            quit) exit 0 ;;
            *) ;;
          esac
        done
        exit 0

        """

        try contents.write(to: scriptURL, atomically: true, encoding: .utf8)
        return Launch(executable: shell, arguments: [scriptURL.path], scriptURL: scriptURL)
    }

    /// The fractional-seconds string `sleep` takes, e.g. "0.05".
    private static func delayString(forMilliseconds ms: Int) -> String {
        guard ms > 0 else { return "0" }
        return String(format: "%g", Double(ms) / 1000.0)
    }
}
